//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapaMichaels.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid OrderId { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Crust { get; set; }
        public Nullable<bool> Sausage { get; set; }
        public Nullable<bool> Pepperoni { get; set; }
        public Nullable<bool> Onions { get; set; }
        public Nullable<bool> GreenPeppers { get; set; }
        public decimal TotalCost { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<bool> Completed { get; set; }
    }
}
